### PR TITLE
delete pdf links from morrison

### PR DESCRIPTION
**Pull request by regineheberlein**

### CODE REVIEW

**Review by sandbergja — COMMENTED** [review]
Looks good!  I was wondering what the relationship is between the two `remove_digital_objects_linked_to_a_resource.rb` files is.  Is one an earlier draft?

**Comment by regineheberlein** [comment]
How odd. There shouldn't be two! There aren't in my local branch. Is git showing two states of the same file?

**Comment by sandbergja** [comment]
Weird! I was looking here: https://github.com/pulibrary/aspace_helpers/pull/208/files

Maybe you can force push your local branch?  Or cherry-pick the last two commits into a new, clean, branch?

**Comment by regineheberlein** [comment]
I think this did it...

**Review by sandbergja — APPROVED** [review]

**Comment by sandbergja** [comment]
Looks great.  Thanks, @regineheberlein

**Comment by regineheberlein** [comment]
Yes, I see it too! Though they’re both in the same directory, and have the same name, so that shouldn’t be possible... I’ll wrap my head around it on Monday. Thanks for the review! Have a good weekend. :-)

Regine Heberlein (she/her)
Library IT Data Analyst
609-258-6156
***@***.******@***.***>

**My working day may not be your working day. Please do not feel obliged to reply to this email outside of your normal working hours.**



From: Jane Sandberg ***@***.***>
Reply-To: pulibrary/aspace_helpers ***@***.***>
Date: Friday, May 6, 2022 at 8:15 PM
To: pulibrary/aspace_helpers ***@***.***>
Cc: "Regine I. Heberlein" ***@***.***>, Author ***@***.***>
Subject: Re: [pulibrary/aspace_helpers] delete pdf links from morrison (PR #208)


Weird! I was looking here: https://github.com/pulibrary/aspace_helpers/pull/208/files<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpulibrary%2Faspace_helpers%2Fpull%2F208%2Ffiles&data=05%7C01%7Cheberlei%40princeton.edu%7C9a32ef27cdce47242a0708da2fbea993%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C637874793202300093%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ENpmOJJLFec7tJ7Q9NQyAQruOxJ%2BRqLurZ9v1K7HsRs%3D&reserved=0>

Maybe you can force push your local branch? Or cherry-pick the last two commits into a new, clean, branch?

**Pull request merged**
