### PR TITLE
Items

### PR DESCRIPTION
**Pull request by regineheberlein**

### CODE REVIEW

**Review by sandbergja — COMMENTED** [review]
@regineheberlein It seems like a lot of shared code between get_MARCxml.rb and get_MARCxml_with_items.rb, and I'm concerned that keeping them in sync could be a maintenance burden.  Would it make sense to merge them into a single process that optionally accepts a "with_items" option?

**Comment by regineheberlein** [comment]
Thanks @sandbergja! You're absolutely right, and (I think) eventually we'll want to replace the process that's running now with the with_items process. However, there's going to be an overlap period where we will run the with_items process manually to stress-test it--to commence once the PR is approved and the locations are finalized. 

(There is also an Alma consideration such that it *may* need to remain a separate process, which is also TBD.)

My goal with this PR is to get the process ready to be run manually to initiate the manual phase; then sort out next steps based on the outcome of that trial run.

**Review by sandbergja — APPROVED** [review]
Thanks @regineheberlein !

**Comment by regineheberlein** [comment]
Thank you @sandbergja !

**Pull request merged**
